#!/usr/bin/env python3
"""wp-qa-skills setup wizard.

Run after install.sh:
  python3 setup.py
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path


# ── helpers ──────────────────────────────────────────────

def ask(msg, default=None):
    hint = f" [{default}]" if default is not None else ""
    try:
        v = input(f"{msg}{hint}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)
    return v if v else (str(default) if default is not None else "")


def yn(msg, default=True):
    hint = "[Y/n]" if default else "[y/N]"
    try:
        v = input(f"{msg} {hint}: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)
    return default if not v else v[0] == "y"


def sep(title):
    pad = max(50 - len(title) - 4, 2)
    print(f"\n── {title} {'─' * pad}")


def run(*args, cwd=None):
    r = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    return r.returncode, r.stdout.strip()


def run_live(*args, cwd=None):
    return subprocess.run(args, cwd=cwd).returncode


def num(msg, default):
    while True:
        v = ask(msg, str(default))
        if v.isdigit():
            return int(v)
        print("  Enter a whole number.")


# ── config templates ─────────────────────────────────────

def site_audit_config(c):
    t = c["thresholds"]

    def th(k, d):
        return t.get(k, d)

    return f"""\
# Site Audit Configuration

**Copy this file to new projects and fill in the blanks.** Every setting marked `REQUIRED` must be set before first run.

## REQUIRED — Site Identity

| Setting | Value | Description |
|---------|-------|-------------|
| `base_url` | `{c['base_url']}` | Site base URL, e.g. `https://mysite.local` |
| `wp_root` | `{c['wp_root']}` | Path to WordPress root (relative or absolute) |

## REQUIRED — URL Scope

| Setting | Value | Description |
|---------|-------|-------------|
| `url_source` | `{c['url_source']}` | `sitemap`, `file:<path>`, or comma-separated list |
| `max_urls` | `{c['max_urls']}` | Cap URLs to crawl — set based on site size (50, 200, 500) |

No default `max_urls` — you choose. Small site: 50. Medium: 200. Large: 500+.

## REQUIRED — Fix Loop Iteration Cap

| Setting | Value | Description |
|---------|-------|-------------|
| `max_iterations` | `{c['max_iterations']}` | Max fix loop iterations — recommend 2x `max_urls` |
| `max_fix_attempts` | `{c['max_fix_attempts']}` | Attempts per error before skipping |

## Thresholds (RED)

Tune these to your site's performance profile. A WooCommerce site with 200 queries might be normal. A brochure site with 50 might be bloated.

| Metric | Default | Notes |
|--------|---------|-------|
| `query_count` | > {th('query_count', 100)} | Total DB queries per page |
| `duplicate_queries` | > {th('duplicate_queries', 5)} | Duplicate query patterns |
| `slow_query_ms` | > {th('slow_query_ms', 50)} | Any single query over this (0.05s) |
| `ttfb_ms` | > {th('ttfb_ms', 500)} | Time to first byte |
| `load_ms` | > {th('load_ms', 3000)} | Full page load |
| `memory_mb` | > {th('memory_mb', 64)} | PHP memory usage |
| `peak_memory_mb` | > {th('peak_memory_mb', 128)} | Peak PHP memory |
| `php_errors` | > {th('php_errors', 0)} | Any PHP error/warning/notice |
| `js_errors` | > {th('js_errors', 0)} | Any JS console error or exception |

AMBER: within 70% of RED threshold.

Override via `thresholds.json`:
```json
{{
  "query_count": 150,
  "slow_query_ms": 100
}}
```
Pass with: `python3 audit.py --thresholds thresholds.json`

## Log Paths (auto-detected, override if different)

| Source | Default path | Notes |
|--------|-------------|-------|
| QM JSON output | `wp-content/qm-output/*.json` | Core data source — must exist |
| JS errors | `wp-content/qm-output/js-errors.json` | Generated by Playwright crawl |
| PHP debug log | `wp-content/debug.log` | Requires WP_DEBUG_LOG enabled |
| PHP error log | `logs/php-error.log` | Local by Flywheel default |
| Access log | `logs/access.log` | Optional context |

Override any path in `audit.py` with `--qm-dir`, `--debug-log`, `--php-log`, `--access-log`.

## QM Auth Cookie

```
QM_COOKIE = {{ name: 'qm_auth', value: '1' }}
```

Value must match whatever the QM mu-plugin checks. Any truthy value works with the default mu-plugin.

## Pre-Audit Checklist

- [ ] Caching plugins disabled (W3 Total Cache, WP Rocket, etc.)
- [ ] `QM_DB_EXPENSIVE=0.05` or your threshold in wp-config.php
- [ ] QM JSON dispatcher mu-plugin active
- [ ] `wp-content/qm-output/` directory exists and is writable
- [ ] Sitemap accessible (WordPress default: `/wp-sitemap.xml`)
- [ ] `QM_COOKIE` value in mu-plugin matches crawl cookie value
- [ ] Playwright installed: `cd tests/playwright && npm install`

## Playwright Crawl Config

Edit `tests/playwright/src/crawl.spec.ts` before running:
- `BASE`: your site URL (must match `base_url` above)
- `MAX_URLS`: pull from `max_urls` setting above
- `QM_COOKIE`: must match mu-plugin

See `references/playwright-crawl.md` for setup instructions.

## Environment Overrides

Same config file. Add your environments:

```
## Environment-Specific
| Setting | Local | Staging | Production |
|---------|-------|---------|------------|
| `wp_root` | `.` | `/path/to/staging/` | `/path/to/production/` |
| `base_url` | `https://mysite.local` | `https://staging.mysite.com` | `https://mysite.com` |
```
"""


def bugherd_config(b):
    api_key = b.get("api_key", "**REQUIRED — set before use**")
    proj_name = b.get("project_name", "my-project")
    proj_id = b.get("project_id", "**REQUIRED**")
    return f"""\
# BugHerd Fix Pipeline Configuration

## Mode Support

This skill operates in two modes:
- **BugHerd mode** (task ID provided) — requires this CONFIG.md with valid API key
- **Plain text mode** (bug described in words) — CONFIG.md optional, no API calls

If CONFIG.md doesn't exist or API key is missing, plain text mode still works fully — just skip BugHerd handoff.

## BugHerd API

| Setting | Value | Description |
|---------|-------|-------------|
| `api_base` | `https://www.bugherd.com/api_v2` | REST API v2 base |
| `api_key` | {api_key} | API key from BugHerd settings |
| `auth_header` | `Basic <base64(api_key:x)>` | Basic auth with API key as username |

Get your API key: BugHerd > Settings > API Keys.

## Project IDs

| Project | ID | Description |
|---------|-----|-------------|
| `{proj_name}` | {proj_id} | Your project name here |

Find project IDs: `GET /api_v2/projects.json` with your API key.

## Status Mappings

BugHerd uses a column/status model where each project has its own column structure.
Fetch yours: `GET /api_v2/projects/{{id}}/columns.json`

Standard BugHerd status flow:

| Phase | BugHerd Status | Description |
|-------|---------------|-------------|
| Before fix | `todo` | Task awaiting fix |
| During fix | `doing` | Fix in progress |
| After fix | `feedback` | Fix applied, needs verification |
| Verified | `done` | QA verified |

**IMPORTANT:** BugHerd uses columns, not status transitions. To change status, update the task's `column_id`:
```
PUT /api_v2/projects/{{project_id}}/tasks/{{task_id}}.json
Body: {{"task": {{"column_id": <id>}}}}
```

## Team Members

| Alias | BugHerd ID | Role |
|-------|-----------|------|
| `dev` | (set your ID) | Developer |
| `qa` | (set QA ID) | QA reviewer |

Find user IDs: `GET /api_v2/projects/{{id}}/members.json`

## Branch Strategy

| Parameter | Behaviour |
|-----------|----------|
| `ask` (default) | Prompt user to choose main/new/worktree |
| `main` | Commit directly to main |
| `new` | Create `fix/{{YYYY-MM-DD}}-BH-{{id}}` branch |
| `worktree` | Isolated worktree |

## Commit Convention

```
fix: <description> [BH-{{id}}]

Co-Authored-By: Claude <noreply@anthropic.com>
```

## BugHerd Comment Format

After fix, post comment with:
- What was fixed (root cause + solution)
- Commit hash
- Files changed
- QA verification steps
- Review findings summary

## Test BugHerd Task

For testing the pipeline: use a BugHerd task with minimal complexity.
Example: `BH-1` (text change, CSS fix, etc.)
"""


def write_configs(base, site_cfg, bugherd_cfg):
    sa = site_audit_config(site_cfg)
    bh = bugherd_config(bugherd_cfg)
    locations = [
        (Path(base) / "skills" / "site-audit" / "CONFIG.md", sa),
        (Path(base) / ".claude" / "skills" / "site-audit" / "CONFIG.md", sa),
        (Path(base) / "skills" / "fix-bugherd" / "CONFIG.md", bh),
        (Path(base) / ".claude" / "skills" / "fix-bugherd" / "CONFIG.md", bh),
    ]
    written = []
    for p, content in locations:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
        written.append(str(p.relative_to(base)))
    return written


# ── main wizard ──────────────────────────────────────────

def main():
    base = str(Path.cwd())
    print("\n  wp-qa-skills setup")
    print("  ==================")

    # 1. WP root detection
    if not (Path(base) / "wp-content").is_dir():
        print(f"[WARN] wp-content/ not found at {base}")
        alt = ask("WordPress root path", ".")
        if alt and alt != ".":
            candidate = Path(alt) if Path(alt).is_absolute() else Path(base) / alt
            base = str(candidate)

    # 2. Site identity
    sep("Site Identity")
    base_url = ask("base_url", "https://mysite.local")
    wp_root = ask("wp_root", ".")

    # 3. URL scope
    sep("URL Scope")
    print("  source options: sitemap | file:<path> | comma-separated URLs")
    url_source = ask("url_source", "sitemap")
    print("  guide: Small (<50 pages)=50  Medium=200  Large=500")
    max_urls = num("max_urls (required)", 50)

    # 4. Fix loop
    sep("Fix Loop")
    max_iterations = num("max_iterations", max_urls * 2)
    max_fix_attempts = num("max_fix_attempts", 3)

    # 5. Thresholds
    sep("Thresholds")
    thresholds = {}
    if yn("Tune thresholds?", False):
        for key, default in [
            ("query_count", 100), ("duplicate_queries", 5), ("slow_query_ms", 50),
            ("ttfb_ms", 500), ("load_ms", 3000), ("memory_mb", 64),
            ("peak_memory_mb", 128), ("php_errors", 0), ("js_errors", 0),
        ]:
            v = ask(f"  {key}", str(default))
            try:
                thresholds[key] = int(v)
            except ValueError:
                thresholds[key] = default

    # 6. BugHerd
    sep("BugHerd (optional)")
    bugherd = {}
    if yn("Use BugHerd?", False):
        bugherd["enabled"] = True
        bugherd["api_key"] = ask("  api_key")
        bugherd["project_name"] = ask("  project name", "my-project")
        bugherd["project_id"] = ask("  project ID")

    # 7. Git remote
    sep("Git Remote")
    code, remote = run("git", "remote", "get-url", "origin", cwd=base)
    current_remote = remote if code == 0 else None
    if current_remote:
        print(f"  origin: {current_remote}")
        if not yn("Correct?", True):
            new = ask("  New remote URL", "")
            if new:
                run_live("git", "remote", "set-url", "origin", new, cwd=base)
                current_remote = new
    else:
        print("  No git remote set.")
        new = ask("  Add remote URL (Enter to skip)", "")
        if new:
            run_live("git", "remote", "add", "origin", new, cwd=base)
            current_remote = new

    # 8. Log checks
    sep("Log Sources")
    debug_log = Path(base) / "wp-content" / "debug.log"
    if debug_log.exists():
        lines = sum(1 for _ in open(debug_log, errors="replace"))
        mb = debug_log.stat().st_size / 1024 / 1024
        print(f"[OK  ] wp-content/debug.log ({lines} lines, {mb:.1f}MB)")
    else:
        print("[WARN] wp-content/debug.log not found")
        print("       define('WP_DEBUG', true); define('WP_DEBUG_LOG', true);")

    for label, rel in [("logs/php-error.log", "logs/php-error.log"),
                        ("logs/access.log", "logs/access.log")]:
        p = Path(base) / rel
        print(f"[{'OK  ' if p.exists() else 'WARN'}] {label}{'  found' if p.exists() else ' not found'}")

    wp_cfg = Path(base) / "wp-config.php"
    if wp_cfg.exists():
        text = wp_cfg.read_text(errors="replace")
        for key in ("WP_DEBUG", "WP_DEBUG_LOG"):
            pat = r"define\s*\(\s*['\"]" + key + r"['\"]\s*,\s*true\s*\)"
            found = bool(re.search(pat, text))
            print(f"[{'OK  ' if found else 'WARN'}] {key} = {'true' if found else 'not set'}")

    # 9. Playwright
    sep("Playwright")
    playwright_dir = Path(base) / "tests" / "playwright"
    has_node = run("node", "--version")[0] == 0
    print(f"[{'OK  ' if has_node else 'WARN'}] Node {'available' if has_node else 'not found — install Node.js'}")

    if playwright_dir.exists():
        nm = playwright_dir / "node_modules"
        if nm.exists():
            print("[OK  ] node_modules found")
        elif has_node and yn("Install Playwright deps now?", True):
            try:
                run_live("npm", "install", cwd=str(playwright_dir))
                run_live("npx", "playwright", "install", "chromium", cwd=str(playwright_dir))
                print("[OK  ] Playwright installed")
            except Exception as e:
                print(f"[WARN] Install failed: {e}")
                print(f"       Manual: cd {playwright_dir} && npm install && npx playwright install chromium")
        else:
            print(f"[WARN] Run: cd {playwright_dir} && npm install && npx playwright install chromium")
    else:
        print("[WARN] tests/playwright/ not found — run install.sh first")

    # 10. QM mu-plugin + output directory
    sep("Query Monitor mu-plugin")
    mu_dst = Path(base) / "wp-content" / "mu-plugins" / "qm-perf-capture.php"
    mu_src = Path(base) / "skills" / "site-audit" / "mu-plugins" / "qm-perf-capture.php"
    if mu_dst.exists():
        print("[OK  ] qm-perf-capture.php installed")
    elif mu_src.exists():
        mu_dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(str(mu_src), str(mu_dst))
        print("[OK  ] qm-perf-capture.php copied to wp-content/mu-plugins/")
    else:
        print("[WARN] qm-perf-capture.php missing — copy from skills/site-audit/mu-plugins/")

    # Create qm-output/ dir — mu-plugin writes here during Playwright crawl
    qm_output = Path(base) / "wp-content" / "qm-output"
    qm_output.mkdir(parents=True, exist_ok=True)
    print("[OK  ] wp-content/qm-output/ ready")

    qm_plugin_dir = Path(base) / "wp-content" / "plugins" / "query-monitor"
    if qm_plugin_dir.exists():
        print("[OK  ] Query Monitor plugin found")
    else:
        code_wp, _ = run("wp", "--version", cwd=base)
        if code_wp == 0 and yn("Install Query Monitor via WP-CLI?", True):
            run_live("wp", "plugin", "install", "query-monitor", "--activate", cwd=base)
        else:
            print("[WARN] Install Query Monitor: WP Admin > Plugins > Add New")

    # 11. Custom URL list (only if url_source looks like a custom list trigger)
    if url_source not in ("sitemap",) and not url_source.startswith("file:") and "," not in url_source:
        sep("Custom URL List")
        print("  Enter URLs one per line. Empty line to finish:")
        crawl_urls = []
        while True:
            try:
                u = input("  URL: ").strip()
            except (EOFError, KeyboardInterrupt):
                break
            if not u:
                break
            crawl_urls.append(u)
        if crawl_urls and playwright_dir.exists():
            env_path = playwright_dir / ".env"
            existing = env_path.read_text() if env_path.exists() else ""
            existing = re.sub(r"^CRAWL_URLS=.*\n?", "", existing, flags=re.M)
            env_path.write_text(existing + f"CRAWL_URLS={','.join(crawl_urls)}\n")
            print(f"[OK  ] CRAWL_URLS written to tests/playwright/.env ({len(crawl_urls)} URLs)")

    # 12. Write CONFIG.md files
    sep("Writing Config Files")
    site_cfg = {
        "base_url": base_url,
        "wp_root": wp_root,
        "url_source": url_source,
        "max_urls": max_urls,
        "max_iterations": max_iterations,
        "max_fix_attempts": max_fix_attempts,
        "thresholds": thresholds,
    }
    written = write_configs(base, site_cfg, bugherd)
    for f in written:
        print(f"[OK  ] {f}")

    # 13. Summary
    sep("Done")
    print(f"  base_url:       {base_url}")
    print(f"  max_urls:       {max_urls}")
    print(f"  max_iterations: {max_iterations}")
    print(f"  BugHerd:        {'configured' if bugherd.get('enabled') else 'skipped'}")
    print(f"  git remote:     {current_remote or 'none'}")
    print()
    print("  Next: restart Claude Code, then run /site-audit")
    print()


if __name__ == "__main__":
    main()
